stages:
  data_ingestion:
    cmd: python main.py data_ingestion
    deps:
      - src/components/data_ingestion.py
      - src/configuration/mongodb_connection.py
      - src/data_access/mongodb_data.py
    params:
      - data_ingestion.train_test_split_ratio
      - data_ingestion.random_state
    outs:
      - artifacts/data_ingestion/feature_store/raw_data.csv
      - artifacts/data_ingestion/ingested/train.csv
      - artifacts/data_ingestion/ingested/test.csv

  data_validation:
    cmd: python main.py data_validation
    deps:
      - src/components/data_ingestion.py
      - src/components/data_validation.py
    outs:
      - artifacts/data_validation/validation_report.json

  data_transformation:
    cmd: python main.py data_transformation
    deps:
      - src/components/data_ingestion.py
      - src/components/data_validation.py
      - src/components/data_transformation.py
    outs:
      - artifacts/data_transformation/transformed_data/train.npy
      - artifacts/data_transformation/transformed_data/test.npy
      - artifacts/data_transformation/transformation_objects/preprocessing.pkl

  model_trainer:
    cmd: python main.py model_trainer
    deps:
      - src/components/data_ingestion.py
      - src/components/data_validation.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py
    params:
      - model_trainer.model_params
      - model_trainer.expected_score
    outs:
      - artifacts/model_trainer/trained_model/model.pkl

  model_evaluation:
    cmd: python main.py model_evaluation
    deps:
      - src/components/data_ingestion.py
      - src/components/data_validation.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py
      - src/components/model_evaluation.py
    params:
      - model_evaluation.changed_threshold_score
    outs:
      - artifacts/model_evaluation/model_evaluation_report.pkl

  model_pusher:
    cmd: python main.py model_pusher
    deps:
      - src/components/data_ingestion.py
      - src/components/data_validation.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py
      - src/components/model_evaluation.py
      - src/components/model_pusher.py